/* @ author : Yash Pahwa
@email: yashpahwa.work@gmail.com
mobile : +91 8802444447
Thapar Institute of Engineering and Technology
*/

/*
 * Service: auditLogService
 * Purpose: Simulates a backend API service for audit log data in the LMS platform.
 * It manages local storage caching, simulated network latency, and handles
 * fetching, filtering, sorting, and paginating audit log entries.
 * Features: Mock audit log seed data, stats computation, and detail lookup by audit ID.
 */
import { STORAGE_KEY } from '@/AuditLog/constants.js';
import { computeStats, filterLogs, paginateLogs, sortLogs } from '@/AuditLog/utils/auditHelpers.js';

const delay = (ms = 400) => new Promise((resolve) => setTimeout(resolve, ms));

const getStorageItem = (key, fallback) => {
  const data = localStorage.getItem(key);
  if (!data) {
    localStorage.setItem(key, JSON.stringify(fallback));
    return fallback;
  }
  try {
    return JSON.parse(data);
  } catch {
    return fallback;
  }
};

const now = Date.now();
const hoursAgo = (hours) => new Date(now - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (days) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export const initialAuditLogs = [
  {
    auditId: 'AUD-20260709-0001',
    timestamp: hoursAgo(0.5),
    userName: 'Priya Sharma',
    email: 'priya.sharma@xebia.com',
    role: 'Super Admin',
    module: 'Identity & Access',
    submodule: 'RBAC',
    action: 'UPDATE',
    entity: 'Role',
    entityId: 'ROLE-001',
    status: 'SUCCESS',
    ipAddress: '103.21.45.88',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Gurugram, IN',
    traceId: 'tr-8f3a2c1b9d4e',
    description: 'Updated permission grants for Manager role',
    metadata: { changedFields: ['permissions'], grantCount: 12 },
  },
  {
    auditId: 'AUD-20260709-0002',
    timestamp: hoursAgo(1),
    userName: 'Rajesh Kumar',
    email: 'rajesh.kumar@xebia.com',
    role: 'Admin',
    module: 'Workforce',
    submodule: 'Onboarding',
    action: 'CREATE',
    entity: 'Trainer',
    entityId: 'TRN-442',
    status: 'SUCCESS',
    ipAddress: '49.36.112.45',
    browser: 'Firefox 127',
    device: 'Desktop',
    location: 'Pune, IN',
    traceId: 'tr-1a2b3c4d5e6f',
    description: 'Onboarded new trainer to Acme Corp organisation',
    metadata: { organisationId: 'ORG-12', trainerId: 'TRN-442' },
  },
  {
    auditId: 'AUD-20260709-0003',
    timestamp: hoursAgo(2),
    userName: 'Anita Desai',
    email: 'anita.desai@xebia.com',
    role: 'Manager',
    module: 'Scheduling',
    submodule: 'Booking',
    action: 'APPROVE',
    entity: 'Training Session',
    entityId: 'SES-8891',
    status: 'SUCCESS',
    ipAddress: '182.76.34.21',
    browser: 'Safari 17',
    device: 'Tablet',
    location: 'Mumbai, IN',
    traceId: 'tr-7g8h9i0j1k2l',
    description: 'Approved conflict-free training proposal for Batch B-204',
    metadata: { batchId: 'B-204', trainerId: 'TRN-201' },
  },
  {
    auditId: 'AUD-20260709-0004',
    timestamp: hoursAgo(3),
    userName: 'Vikram Singh',
    email: 'vikram.singh@xebia.com',
    role: 'Organiser',
    module: 'Courses',
    submodule: 'Curriculum',
    action: 'UPDATE',
    entity: 'Course',
    entityId: 'CRS-105',
    status: 'FAILED',
    ipAddress: '117.192.88.67',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Bangalore, IN',
    traceId: 'tr-m3n4o5p6q7r8',
    description: 'Failed to assign curriculum — version conflict detected',
    metadata: { errorCode: 'VERSION_CONFLICT', courseVersion: 3 },
  },
  {
    auditId: 'AUD-20260709-0005',
    timestamp: hoursAgo(4),
    userName: 'Sarah Jenkins',
    email: 's.jenkins@xebia.com',
    role: 'Trainer',
    module: 'Assessment',
    submodule: 'Evaluation',
    action: 'UPDATE',
    entity: 'Assessment Score',
    entityId: 'ASM-3340',
    status: 'SUCCESS',
    ipAddress: '203.45.67.89',
    browser: 'Edge 126',
    device: 'Desktop',
    location: 'Hyderabad, IN',
    traceId: 'tr-s9t0u1v2w3x4',
    description: 'Overrode AI evaluation score for learner attempt',
    metadata: { originalScore: 72, overrideScore: 85, reason: 'Manual review' },
  },
  {
    auditId: 'AUD-20260709-0006',
    timestamp: hoursAgo(5),
    userName: 'Michael Chen',
    email: 'm.chen@xebia.com',
    role: 'Learner',
    module: 'Identity & Access',
    submodule: 'Authentication',
    action: 'LOGIN',
    entity: 'User Session',
    entityId: 'SES-LRN-9912',
    status: 'SUCCESS',
    ipAddress: '45.120.33.14',
    browser: 'Chrome Mobile 126',
    device: 'Mobile',
    location: 'Delhi, IN',
    traceId: 'tr-y5z6a7b8c9d0',
    description: 'Successful login via SSO',
    metadata: { authMethod: 'SSO', mfaVerified: true },
  },
  {
    auditId: 'AUD-20260709-0007',
    timestamp: hoursAgo(6),
    userName: 'Alex Rivera',
    email: 'a.rivera@xebia.com',
    role: 'Admin',
    module: 'Finance',
    submodule: 'Invoicing',
    action: 'EXPORT',
    entity: 'Invoice Report',
    entityId: 'INV-RPT-2026Q2',
    status: 'SUCCESS',
    ipAddress: '98.76.54.32',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Chennai, IN',
    traceId: 'tr-e1f2g3h4i5j6',
    description: 'Exported Q2 invoice reconciliation report',
    metadata: { format: 'CSV', recordCount: 248 },
  },
  {
    auditId: 'AUD-20260709-0008',
    timestamp: hoursAgo(8),
    userName: 'Unknown User',
    email: null,
    role: null,
    module: 'Identity & Access',
    submodule: 'Authentication',
    action: 'LOGIN',
    entity: 'User Session',
    entityId: null,
    status: 'CRITICAL',
    ipAddress: '185.220.101.42',
    browser: 'Unknown',
    device: 'Desktop',
    location: 'Unknown',
    traceId: 'tr-k7l8m9n0o1p2',
    description: 'Multiple failed login attempts — account lockout triggered',
    metadata: { attemptCount: 5, lockoutDuration: '30m' },
  },
  {
    auditId: 'AUD-20260709-0009',
    timestamp: hoursAgo(10),
    userName: 'Elena Rostova',
    email: 'e.rostova@xebia.com',
    role: 'Trainer',
    module: 'Courses',
    submodule: 'Authoring',
    action: 'CREATE',
    entity: 'Module',
    entityId: 'MOD-778',
    status: 'SUCCESS',
    ipAddress: '112.45.78.90',
    browser: 'Firefox 127',
    device: 'Desktop',
    location: 'Kolkata, IN',
    traceId: 'tr-q3r4s5t6u7v8',
    description: 'Created new course module with 8 submodules',
    metadata: { courseId: 'CRS-220', moduleCount: 8 },
  },
  {
    auditId: 'AUD-20260709-0010',
    timestamp: hoursAgo(12),
    userName: 'David Vance',
    email: 'd.vance@xebia.com',
    role: 'Manager',
    module: 'Workforce',
    submodule: 'Enrolment',
    action: 'DELETE',
    entity: 'Batch Enrolment',
    entityId: 'ENR-5567',
    status: 'WARNING',
    ipAddress: '67.89.12.34',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Jaipur, IN',
    traceId: 'tr-w9x0y1z2a3b4',
    description: 'Removed learner from batch — pending approval notification sent',
    metadata: { batchId: 'B-118', learnerId: 'LRN-903' },
  },
  {
    auditId: 'AUD-20260708-0011',
    timestamp: daysAgo(1),
    userName: 'Priya Sharma',
    email: 'priya.sharma@xebia.com',
    role: 'Super Admin',
    module: 'Analytics',
    submodule: 'Reports',
    action: 'EXPORT',
    entity: 'Dashboard Report',
    entityId: 'RPT-DASH-001',
    status: 'SUCCESS',
    ipAddress: '103.21.45.88',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Gurugram, IN',
    traceId: 'tr-c5d6e7f8g9h0',
    description: 'Exported leadership dashboard snapshot',
    metadata: { format: 'PDF', scope: 'enterprise' },
  },
  {
    auditId: 'AUD-20260708-0012',
    timestamp: daysAgo(1),
    userName: 'Marcus MesCaline',
    email: 'm.mescaline@xebia.com',
    role: 'Trainer',
    module: 'Scheduling',
    submodule: 'Availability',
    action: 'UPDATE',
    entity: 'Trainer Slot',
    entityId: 'SLT-3344',
    status: 'SUCCESS',
    ipAddress: '54.32.10.98',
    browser: 'Safari 17',
    device: 'Desktop',
    location: 'Ahmedabad, IN',
    traceId: 'tr-i1j2k3l4m5n6',
    description: 'Updated weekly availability slots',
    metadata: { slotsUpdated: 6 },
  },
  {
    auditId: 'AUD-20260707-0013',
    timestamp: daysAgo(2),
    userName: 'Apurv Jha',
    email: 'a.jha@xebia.com',
    role: 'Admin',
    module: 'Identity & Access',
    submodule: 'Users',
    action: 'DELETE',
    entity: 'User',
    entityId: 'USR-8890',
    status: 'CRITICAL',
    ipAddress: '78.90.12.45',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Noida, IN',
    traceId: 'tr-o7p8q9r0s1t2',
    description: 'Permanently deleted inactive user account',
    metadata: { retentionPolicy: 'GDPR', backupCreated: true },
  },
  {
    auditId: 'AUD-20260707-0014',
    timestamp: daysAgo(2),
    userName: 'Anita Desai',
    email: 'anita.desai@xebia.com',
    role: 'Manager',
    module: 'Assessment',
    submodule: 'Authoring',
    action: 'CREATE',
    entity: 'Test',
    entityId: 'TST-1122',
    status: 'SUCCESS',
    ipAddress: '182.76.34.21',
    browser: 'Edge 126',
    device: 'Desktop',
    location: 'Mumbai, IN',
    traceId: 'tr-u3v4w5x6y7z8',
    description: 'Created timed assessment with 25 questions',
    metadata: { questionCount: 25, durationMinutes: 60 },
  },
  {
    auditId: 'AUD-20260706-0015',
    timestamp: daysAgo(3),
    userName: 'Rajesh Kumar',
    email: 'rajesh.kumar@xebia.com',
    role: 'Admin',
    module: 'Workforce',
    submodule: 'Assignment',
    action: 'UPDATE',
    entity: 'Trainer Assignment',
    entityId: 'ASG-445',
    status: 'FAILED',
    ipAddress: '49.36.112.45',
    browser: 'Firefox 127',
    device: 'Desktop',
    location: 'Pune, IN',
    traceId: 'tr-a9b0c1d2e3f4',
    description: 'Failed trainer assignment — organisation seat limit exceeded',
    metadata: { errorCode: 'SEAT_LIMIT', availableSeats: 0 },
  },
  {
    auditId: 'AUD-20260706-0016',
    timestamp: daysAgo(3),
    userName: 'Michael Chen',
    email: 'm.chen@xebia.com',
    role: 'Learner',
    module: 'Courses',
    submodule: 'Progress',
    action: 'UPDATE',
    entity: 'Course Progress',
    entityId: 'PRG-7788',
    status: 'SUCCESS',
    ipAddress: '45.120.33.14',
    browser: 'Chrome Mobile 126',
    device: 'Mobile',
    location: 'Delhi, IN',
    traceId: 'tr-g5h6i7j8k9l0',
    description: 'Completed module 3 of Enterprise React course',
    metadata: { courseId: 'CRS-001', moduleProgress: 75 },
  },
  {
    auditId: 'AUD-20260705-0017',
    timestamp: daysAgo(4),
    userName: 'Sarah Jenkins',
    email: 's.jenkins@xebia.com',
    role: 'Trainer',
    module: 'Scheduling',
    submodule: 'Conflict',
    action: 'UPDATE',
    entity: 'Booking',
    entityId: 'BKG-9900',
    status: 'WARNING',
    ipAddress: '203.45.67.89',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Hyderabad, IN',
    traceId: 'tr-m1n2o3p4q5r6',
    description: 'Rescheduled session due to trainer conflict resolution',
    metadata: { originalSlot: '2026-07-10T09:00:00Z', newSlot: '2026-07-10T14:00:00Z' },
  },
  {
    auditId: 'AUD-20260705-0018',
    timestamp: daysAgo(4),
    userName: 'Vikram Singh',
    email: 'vikram.singh@xebia.com',
    role: 'Organiser',
    module: 'Finance',
    submodule: 'Contracts',
    action: 'CREATE',
    entity: 'Contract',
    entityId: 'CNT-2233',
    status: 'SUCCESS',
    ipAddress: '117.192.88.67',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Bangalore, IN',
    traceId: 'tr-s7t8u9v0w1x2',
    description: 'Created enterprise contract for TechCorp Ltd',
    metadata: { contractValue: 2500000, currency: 'INR' },
  },
  {
    auditId: 'AUD-20260704-0019',
    timestamp: daysAgo(5),
    userName: 'Alex Rivera',
    email: 'a.rivera@xebia.com',
    role: 'Admin',
    module: 'Analytics',
    submodule: 'Insights',
    action: 'UPDATE',
    entity: 'Report Schedule',
    entityId: 'SCH-4455',
    status: 'SUCCESS',
    ipAddress: '98.76.54.32',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Chennai, IN',
    traceId: 'tr-y3z4a5b6c7d8',
    description: 'Updated weekly report schedule to Monday 08:00 UTC',
    metadata: { cronExpression: '0 8 * * 1' },
  },
  {
    auditId: 'AUD-20260704-0020',
    timestamp: daysAgo(5),
    userName: 'Elena Rostova',
    email: 'e.rostova@xebia.com',
    role: 'Trainer',
    module: 'Assessment',
    submodule: 'Evaluation',
    action: 'UPDATE',
    entity: 'Assessment Score',
    entityId: 'ASM-5566',
    status: 'SUCCESS',
    ipAddress: '112.45.78.90',
    browser: 'Firefox 127',
    device: 'Desktop',
    location: 'Kolkata, IN',
    traceId: 'tr-e9f0g1h2i3j4',
    description: 'Submitted manual evaluation feedback',
    metadata: { feedbackLength: 342, scoreAdjusted: false },
  },
  {
    auditId: 'AUD-20260703-0021',
    timestamp: daysAgo(6),
    userName: 'Priya Sharma',
    email: 'priya.sharma@xebia.com',
    role: 'Super Admin',
    module: 'Identity & Access',
    submodule: 'Modules',
    action: 'CREATE',
    entity: 'Module Config',
    entityId: 'MCFG-001',
    status: 'SUCCESS',
    ipAddress: '103.21.45.88',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Gurugram, IN',
    traceId: 'tr-k5l6m7n8o9p0',
    description: 'Registered new platform module in access control registry',
    metadata: { moduleKey: 'AUDIT', route: '/audit-log' },
  },
  {
    auditId: 'AUD-20260703-0022',
    timestamp: daysAgo(6),
    userName: 'David Vance',
    email: 'd.vance@xebia.com',
    role: 'Manager',
    module: 'Workforce',
    submodule: 'Approval',
    action: 'APPROVE',
    entity: 'Training Event',
    entityId: 'EVT-7788',
    status: 'SUCCESS',
    ipAddress: '67.89.12.34',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Jaipur, IN',
    traceId: 'tr-q1r2s3t4u5v6',
    description: 'Approved training event for Q3 delivery cycle',
    metadata: { eventDate: '2026-08-15', batchCount: 3 },
  },
  {
    auditId: 'AUD-20260702-0023',
    timestamp: daysAgo(7),
    userName: 'Anita Desai',
    email: 'anita.desai@xebia.com',
    role: 'Manager',
    module: 'Scheduling',
    submodule: 'Booking',
    action: 'DELETE',
    entity: 'Training Session',
    entityId: 'SES-4455',
    status: 'FAILED',
    ipAddress: '182.76.34.21',
    browser: 'Safari 17',
    device: 'Tablet',
    location: 'Mumbai, IN',
    traceId: 'tr-w7x8y9z0a1b2',
    description: 'Failed to cancel session — active learner attempts in progress',
    metadata: { errorCode: 'ACTIVE_ATTEMPTS', attemptCount: 4 },
  },
  {
    auditId: 'AUD-20260702-0024',
    timestamp: daysAgo(7),
    userName: 'Marcus MesCaline',
    email: 'm.mescaline@xebia.com',
    role: 'Trainer',
    module: 'Courses',
    submodule: 'Content',
    action: 'UPDATE',
    entity: 'Media Asset',
    entityId: 'MED-9900',
    status: 'SUCCESS',
    ipAddress: '54.32.10.98',
    browser: 'Chrome 126',
    device: 'Desktop',
    location: 'Ahmedabad, IN',
    traceId: 'tr-c3d4e5f6g7h8',
    description: 'Uploaded revised training video content',
    metadata: { fileSize: '245MB', s3Key: 'courses/mod-778/video-v2.mp4' },
  },
  {
    auditId: 'AUD-20260701-0025',
    timestamp: daysAgo(8),
    userName: 'Rajesh Kumar',
    email: 'rajesh.kumar@xebia.com',
    role: 'Admin',
    module: 'Identity & Access',
    submodule: 'Authentication',
    action: 'LOGOUT',
    entity: 'User Session',
    entityId: 'SES-ADM-1122',
    status: 'SUCCESS',
    ipAddress: '49.36.112.45',
    browser: 'Firefox 127',
    device: 'Desktop',
    location: 'Pune, IN',
    traceId: 'tr-i9j0k1l2m3n4',
    description: 'Admin session terminated — idle timeout',
    metadata: { idleMinutes: 30, terminatedBy: 'system' },
  },
];

function getAllLogs() {
  return getStorageItem(STORAGE_KEY, initialAuditLogs);
}

export const auditLogService = {
  async fetchAuditLogs(params = {}) {
    await delay();

    const allLogs = getAllLogs();
    const filtered = filterLogs(allLogs, params.filters ?? {});
    const sorted = sortLogs(filtered, params.sortField, params.sortDirection);
    const paginated = paginateLogs(sorted, params.page ?? 1, params.pageSize ?? 10);
    const stats = computeStats(allLogs);

    const uniqueUsers = [...new Set(allLogs.map((log) => log.userName).filter(Boolean))].sort((a, b) =>
      a.localeCompare(b)
    );

    return {
      logs: paginated.logs,
      totalRecords: paginated.totalRecords,
      totalPages: paginated.totalPages,
      page: paginated.page,
      rangeStart: paginated.rangeStart,
      rangeEnd: paginated.rangeEnd,
      stats,
      allFilteredLogs: sorted,
      uniqueUsers,
    };
  },

  async fetchAuditLogById(auditId) {
    await delay(200);
    const allLogs = getAllLogs();
    const log = allLogs.find((item) => item.auditId === auditId);
    if (!log) {
      throw new Error(`Audit log ${auditId} not found`);
    }
    return log;
  },
};
